version: '3.3'
services:
  revizoodle-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'revizoodle-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd!'
      # Just for dev !
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : < MySQL Port running' inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
# Names our volume
volumes:
  mysql-data:
